version: 0.2

env:
  variables:
    s3_output: "stuffabout.cloud"
    hugo_version: "0.102.3"

phases:
  install:
    commands:
      - wget "https://github.com/gohugoio/hugo/releases/download/v${hugo_version}/hugo_${hugo_version}_Linux-64bit.deb"
      - sudo dpkg -i hugo_${hugo_version}_Linux-64bit.deb
    finally:
      - hugo version
  build:
    commands:
      - hugo
      - cd public && aws s3 sync . s3://${s3_output} --delete --acl public-read
    finally:
      - echo "Script finished running"